### ISSUE TITLE
Support mplayer2 and mpv

### ISSUE THREAD

**Issue by Nikoli** [kokoko3k/xt7-player#2]
Did not find anything about mplayer2 and mpv in ```git log -p```, please add support for them.

**Comment by kokoko3k** [comment]
Just to let you know that i'm working on the port since some weeks.
I'm not going to use the slave mode but something near (--input switch)
When ready, i think i'll open a new github page for it (no fork or whatever).
Something like xt7-mpv...

**Comment by kokoko3k** [comment]
https://github.com/kokoko3k/xt7-player-mpv
